### ISSUE TITLE
observaciones fuera de geocerca

### ISSUE THREAD

**Issue by NataliaNino** [cabsfk/123SFK#18]
en el mensaje al colocar la observacion dejar 
se ha excluido satisfactoriamente "alias de la ambulancia"
actualmente aparece la observacion

el reporte de las observaciones aparece en el panel de alarmas organizar y dejar en el reporte que al consultar la ambulancia con un link muestre las observaciones de la justificación de fuera de ruta

**Comment by cabsfk** [comment]
Se arreglo el alias, en la exclusión@NataliaNino,  se coloco el reporte exclusión en el menú superior derecho, para todos lo usuarios de ambulancias
