### ISSUE TITLE
historias clinicas

### ISSUE THREAD

**Issue by NataliaNino** [cabsfk/123SFK#21]
la agrupación por dia debe agrupar  el tipo de documento, # documento, Tipo atención y si el tipo es consulta externa  debe agrupar por especialidad para el conteo 

cambiar agrupación persona dia por numero de atenciones
colocar en el panel 

Total de atenciones
# urgencias
# hospitalizaciones
# Consulta Externa

total días
promedio atenciones

**Comment by cabsfk** [comment]
se debe llamas atenciones

**Comment by cabsfk** [comment]
Listo Realizado @NataliaNino
