### ISSUE TITLE
Separador de decimales

### ISSUE THREAD

**Issue by NataliaNino** [cabsfk/123SFK#22]
dejar como separador de decimales coma (,) y separador de miles  punto (.)
en ambulancias para la velocidad dejar sin decimales
en la precisión aproximar a 2 decimales

en historia clínica dejar 2 decimales

**Comment by cabsfk** [comment]
Listo en velocidad se limito a dos caracteres y se cambio  coma (,) y separador de miles punto (.)
en historia clínica no lo deje a dos decimales por que como se habla de personas no ser correcto decir 1,5 personas. pero si le colocoque a todos los datos coma (,) y separador de miles punto (.).

**Comment by cabsfk** [comment]
@NataliaNino
