### ISSUE TITLE
filtros opcionales

### ISSUE THREAD

**Issue by NataliaNino** [cabsfk/123SFK#9]
Adicionar al reporte de ambulancias los siguientes filtros opcionales

ambulancia, provincia, hospital, identificación ambulancia, placa, red de servicio

**Comment by cabsfk** [comment]
se agrego filtros a:
Identificacion ambulancias,
se agrego a el nombre ambulancia 
se agrego el nombre de la provincia y el filtro al que pertenece

falta lo siguiente datos por que con ellos no contamos en la base de datos:
placa
hospital 
red de servicio

**Comment by cabsfk** [comment]
Listo filtros Opciones,falta red de servicio @NataliaNino
